### ISSUE TITLE
Can I exchange the underlying model for data generation?

### ISSUE THREAD

**Issue by gabriead** [lamini-ai/lamini#11]
Hi there,
can I change the model that is being used for data generation? I would like to use the wizardLM model for instance.

**Comment by ninazwei90** [comment]
hey @gabriead thanks for your understanding of our delayed response. We've been cooking up some exciting and powerful features! For the free version, we don't support wizardLM.

We recently released [docs-to-qa](https://github.com/lamini-ai/docs-to-qa) SDK to help you generate qa data based on some raw documents (string, .csv, etc.). Please feel free to have a try and let us know if you run into any issues! 


also, thanks so much for using Lamini and reporting issues! We'd love to learn from you and see how we can improve Lamini for you! If you're open to a 20-30 min chat (in exchange for Lamini free credits), please email me at nina@lamini.ai. Looking forward!!
