### ISSUE TITLE
How to fine tune the model ?

### ISSUE THREAD

**Issue by imrankh46** [lamini-ai/lamini#14]
I fine tune the model with instructions using peft but they performance are not good. Is there any other way to fine tune? 
Without instructions I try small model and they work well but I want to do instructions....

**Comment by MooTong123** [comment]
same question, is there any suggested README.md file to show how to fine tune the model?

**Comment by datalee** [comment]
and which methods to use in the lamini

**Comment by ninazwei90** [comment]
Hey all! @imrankh46 @MooTong123 @datalee Thanks for your understanding of our delayed responses. We've been cooking up a lot of exciting features. Re: how to fine-tune, here is a list of resources to help you fine-tune with Lamini and also learn more about fine-tuning:

1. Many walkthroughs in our docs for finetuning: https://lamini-ai.github.io/Examples/llama_v2_example/ 
2. How to finetune with Lamini: https://www.lamini.ai/blog/free-fast-and-furious-finetuning
3. Finetuning course: https://www.lamini.ai/blog/finetuning-llms-with-our-ceo-sharon-zhou-andrew-ng 

Please let us know if you still need help! Also, thanks so much for using Lamini and reporting issues! We'd love to learn from you and see how we can improve Lamini for you! If you're open to a 20-30 min chat (in exchange for Lamini free credits), please email me at [nina@lamini.ai](mailto:nina@lamini.ai). Looking forward!!

**Comment by ShreyaGupta08** [comment]
@datalee depending on the runner you were using to instantiate the LLM, you can checkout the docs for the methods and arguments.
