### ISSUE TITLE
French Support

### ISSUE THREAD

**Issue by enviz** [lamini-ai/lamini#16]
Thanks for letting us know!
Can it be used for several languages? 

If not, please share the steps on how I can train it for French data.

**Comment by ninazwei90** [comment]
hey @enviz we do not optimize for any language; it really depends on the model itself -- if you find any model that supports french, let us know! I'm closing this issue for now. Please feel free to reach out to me at nina@lamini.ai, we also love to hear your experience and feedback using Lamini!
