### ISSUE TITLE
[Documentation] There is no "About" description on Github repository

### ISSUE THREAD

**Issue by SzilvasiPeter** [lamini-ai/lamini#17]
There is no description under the About panel.
> No description, website, or topics provided.

**Comment by ninazwei90** [comment]
@SzilvasiPeter thank you for your amazing feedback! We will add it soon! In the meantime, learn more about us! https://www.lamini.ai/
https://www.lamini.ai/blog/lamini-amd-paving-the-road-to-gpu-rich-enterprise-llms
https://www.lamini.ai/blog/free-fast-and-furious-finetuning
