### ISSUE TITLE
Error in Code Guru Walkthrough 

### ISSUE THREAD

**Issue by rghosh08** [lamini-ai/lamini#20]
Hello, 

I am trying to implement your code guru walkthrough (https://lamini-ai.github.io/Examples/code_guru/#define-the-llm-interface) and getting the following error. Could you please take a look?

**Inptut**
question = Question(question='LLMEngine.save_data')
function = Function(
    name='__init__',
    code='def __init__(self, builder, name):\n        self.builder = builder\n        self.name = name\n        self.main = Function(program=self, name="main")\n        self.functions = {"main": self.main}\n        self.examples = []'
)
llm.save_data([function])
answer = llm(input=Question(question=question), output_type=Answer)

print(answer)

**Output Error**
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
[/home/ubuntu/lamini/main.ipynb](https://vscode-remote+ssh-002dremote-002b10-002e112-002e30-002e123.vscode-resource.vscode-cdn.net/home/ubuntu/lamini/main.ipynb) Cell 20 line 7
      <a href='[vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=1'>2</a>](vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=1'%3E2%3C/a%3E) function = Function(
      <a href='[vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2'>3</a>](vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=2'%3E3%3C/a%3E)     name='__init__',
      <a href='[vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=3'>4</a>](vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=3'%3E4%3C/a%3E)     code='def __init__(self, builder, name):\n        self.builder = builder\n        self.name = name\n        self.main = Function(program=self, name="main")\n        self.functions = {"main": self.main}\n        self.examples = []'
      <a href='[vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4'>5</a>](vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4'%3E5%3C/a%3E) )
      <a href='[vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=5'>6</a>](vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=5'%3E6%3C/a%3E) llm.save_data([function])
----> <a href='[vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=6'>7</a>](vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=6'%3E7%3C/a%3E) answer = llm(input=Question(question=question), output_type=Answer)
      <a href='[vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=8'>9</a>](vscode-notebook-cell://ssh-remote%2B10.112.30.123/home/ubuntu/lamini/main.ipynb#X25sdnNjb2RlLXJlbW90ZQ%3D%3D?line=8'%3E9%3C/a%3E) print(answer)

File [~/lamini/lib/python3.10/site-packages/llama/types/type.py:18](https://vscode-remote+ssh-002dremote-002b10-002e112-002e30-002e123.vscode-resource.vscode-cdn.net/home/ubuntu/lamini/~/lamini/lib/python3.10/site-packages/llama/types/type.py:18), in Type.__init__(self, *args, **kwargs)
     16     object.__setattr__(self, "__fields_set__", unvalidated.__fields_set__)
     17 else:
---> 18     super().__init__(*args, **kwargs)
     20 self._value = Value(type(self), data=self)

File [~/lamini/lib/python3.10/site-packages/pydantic/main.py:341](https://vscode-remote+ssh-002dremote-002b10-002e112-002e30-002e123.vscode-resource.vscode-cdn.net/home/ubuntu/lamini/~/lamini/lib/python3.10/site-packages/pydantic/main.py:341), in pydantic.main.BaseModel.__init__()

ValidationError: 1 validation error for Question
question
  str type expected (type=type_error.str)

**Comment by omonida** [comment]
Thank you, the documentation has been updated!
