### ISSUE TITLE
playground not working after turning finished

### ISSUE THREAD

**Issue by yangcheng** [lamini-ai/lamini#25]
This is a followup issue on https://github.com/lamini-ai/lamini/issues/24 

Using the colab https://colab.research.google.com/drive/1QMeGzR9FnhNJJFmcHtm9RhFP3vrwIkFn?usp=sharing I was able to finish the training, and eval step works in colab notebook,
 
But playground is not functioning correctly. 

![Screenshot 2023-09-28 at 1 55 27 PM](https://github.com/lamini-ai/lamini/assets/132834/474ee474-b4c8-48d1-b8e1-ed79ffdcf2b0)

Here is the shared link https://app.lamini.ai/share?model_id=2ce3948f4604919804d0c0e422b2410f8940f66e59ac01ced862378de2871274

**Comment by ayushi-lamini** [comment]
Hello. Sorry about this, but this currently works fine for me. Could you please retry and let us know if you see this issue again?

**Comment by Neovalle** [comment]
Hi , I have the same issue too; it worked initially but stopped in the last couple of days. I have trained 3 models and is the same with all three, example app.lamini.ai/share?model_id=b647994dc79521fc3585c7ce17f64153b6022bf31fcc4eb1aea04a9f6aebab57 
Thank you

**Comment by ayushi-lamini** [comment]
Sorry about your experience. We're working on getting a stable/permanent solution for this. Thank you for your patience!

**Comment by yangcheng** [comment]
> Hello. Sorry about this, but this currently works fine for me so can not comment on what went wrong. Perhaps an intermittent issue. Could you please retry and let us know if you see this issue again?

Thanks for the information,  do you mean a seperate training is working fine or the [playground link ](https://app.lamini.ai/share?model_id=2ce3948f4604919804d0c0e422b2410f8940f66e59ac01ced862378de2871274)I posted is working fine ? I retried and the playground link is not working.

**Comment by ninazwei90** [comment]
hey @yangcheng @Neovalle thanks so much for using Lamini and reporting issues! This is Nina, designer from Lamini. We'd love to learn from you and see how we can improve Lamini for you! If you're open to a 20-30 min chat (in exchange for Lamini free credits), please email me at nina@lamini.ai. Looking forward!!

**Comment by ninazwei90** [comment]
Hi all, this should be fixed. Please try again and do reach out if you need any help at nina@lamini.ai. Feel free to try out our examples: https://www.lamini.ai/examples
