### ISSUE TITLE
Colab examples"Question-Answer LLM Finetuning" Error 

### ISSUE THREAD

**Issue by GZDXGeorge** [lamini-ai/lamini#27]
# Problem1:
```
!pip install --upgrade --force-reinstall --ignore-installed lamini
```
When I just run this script,there will be an error:"AttributeError: module 'numpy.linalg._umath_linalg' has no attribute '_ilp64'"<br/>
I have solved this problem by myself.We can change it into 
```
!pip install --upgrade  lamini==0.0.19
```
# Problem2:
![9676bf7266513b6fe234d861ffcdc3b](https://github.com/lamini-ai/lamini/assets/52683131/e24e4683-c8b0-405c-b284-e9a3dd0c20fd)
It's my first time to use lamini,I still have some available credits.
![image](https://github.com/lamini-ai/lamini/assets/52683131/e85ef35b-a666-4042-b177-b21bcecac11c)
![image](https://github.com/lamini-ai/lamini/assets/52683131/8844507b-2ec5-4c80-ad13-ff6c0a1b2513)

Can you tell me how to resolve the problem?

**Comment by ninazwei90** [comment]
@GZDXGeorge hey! this is the correct code -- we recently had a big upgrade of our python library
`!pip install --upgrade --force-reinstall --ignore-installed lamini`

have you tried other colab examples, if so, can you run them? https://www.lamini.ai/examples 

I also have responded to your email -- happy to hop on a call

**Comment by ninazwei90** [comment]
Hey! @GZDXGeorge this should be fixed. Please try again https://www.lamini.ai/examples. Do reach out if you need help at nina@lamini.ai
