### ISSUE TITLE
Pydantic dependency issue

### ISSUE THREAD

**Issue by filopedraz** [lamini-ai/lamini#29]
### Description

I am integrating `lamini` in my python backend, but I cannot because of `lamini` requirements for what concerns Pydantic.

```
lamini 1.0.3 depends on pydantic==1.10.*
```

All my dependencies require `pydantic>=2.x.x`. Can you please upgrade or let me know how to do it?

**Comment by powerjohnnyli** [comment]
pydantic is removed as a dependency

**Comment by edamamez** [comment]
We'd like to offer some Lamini credits as thanks for reaching out!  Please email us at [info@lamini.ai](mailto:info@lamini.ai) and we will send them over 🦙
