### ISSUE TITLE
lamini apis broke on JAn 26, 2024

### ISSUE THREAD

**Issue by Sabk0926** [lamini-ai/lamini#34]
Hello,

I was testing a small RAG bot using lamini APIs and this morning the working code stopped working. Once I updated to lamini python lib version 2.0.8. I am getting API error 502 

Bad Gateway for url: https://api.lamini.ai/v1/inference/embedding

Did the endpoint change? I dont see any document
site-packages\lamini\api\rest_requests.py", line 176, in make_web_request
    raise APIError(f"API error {description}")
lamini.error.error.APIError: API error 502

with a larger txt file I was getting model name error. 

Any guidance please?

**Comment by Sabk0926** [comment]
Now I am getting 

requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.lamini.ai/v1/inference/embedding

**Comment by edamamez** [comment]
Hello, thank you for reaching out! Could you try using version `2.0.7`?

We are actively debugging some issues with `2.0.8` right now.

**Comment by edamamez** [comment]
Following up, the endpoint is correct. Could you try again now?

**Comment by Sabk0926** [comment]
Alright, endpoint is now working and the 2.0.8 is working now.

**Comment by edamamez** [comment]
Great! We'd like to offer some Lamini credits as thanks for reaching out! Please email us at [info@lamini.ai](mailto:info@lamini.ai) and we can send them over 🦙
