### ISSUE TITLE
Unable to import RetrievalAugmentedRunner

### ISSUE THREAD

**Issue by ParthMandaliya** [lamini-ai/lamini#36]
I cannot import `RetrievalAugmentedRunner` and `DirectoryLoader`, `LaminiIndex`, `QueryEngine` these classes also have the same problem.
As per the official documentation, the correct way of importing these classes is directly from the lamini package. Also could not find these classes in the code here in this repo.
I have also raised the same issue [here](https://github.com/lamini-ai/rag-easy-runner/issues/1).

I am running an Ubuntu 22.04 with Python 3.10.13.

If you need any more details, please do let me know.

**Comment by edamamez** [comment]
Hello, thank you for reaching out!

That is correct, we have moved those classes out of the lamini package. You can check out our RAG SDK to see how to write those classes now: https://github.com/lamini-ai/lamini-sdk/blob/main/03_RAG/rag.md

Sorry for the confusion, we are actively updating our docs to keep up with our latest changes.

If you would like some credits as thanks, please reach out to info@lamini.ai!
