### ISSUE TITLE
Not able to train the mistral model

### ISSUE THREAD

**Issue by teja0508** [lamini-ai/lamini#52]
<img width="1357" alt="image" src="https://github.com/lamini-ai/lamini/assets/58974538/2559a705-d33b-475d-99e7-a1c06ccc17f9">

Seeing above error

**Comment by teja0508** [comment]
Details::
Job ID
5932

Model ID
32ec8321e2d3cde284cd89fc554ea9584f859a456e5ecb29e298c5da6282819c


Dataset ID
1a6ae24964be6fee9d29b42523f463efc39840ce61f3849067dbfc1b5ec2fcfa

**Comment by teja0508** [comment]
And every time if i refresh the browser. it is asking for auth. it doesn't require every time right. it should have some timeout.
please check this issue also.

reference img:
<img width="936" alt="image" src="https://github.com/lamini-ai/lamini/assets/58974538/0e64f196-8d64-4f2d-9402-05b2ccff5ad8">

**Comment by edamamez** [comment]
Looking into it, thank you for reporting! 🙌

**Comment by edamamez** [comment]
For the training failure, you should still be able to run inference on the model -- it looks like it failed during eval after the model was checkpointed.

We are working on a fix.

**Comment by teja0508** [comment]
@edamamez can you please show me the sample code for to inference already trained model.
is there any code link. please share here.

**Comment by edamamez** [comment]
Hi @teja0508! On the job in the train tab, you can use the Playground UI:
<img width="1133" alt="Screenshot 2024-04-15 at 10 28 30 AM" src="https://github.com/lamini-ai/lamini/assets/36808054/45bbf08a-7abe-49c5-b4b5-d60dc851dd9f">


If you prefer using Python, you can instantiate and call generate on the model: https://lamini-ai.github.io/lamini_python_class/__call__/

For your model it would be this:
```
from lamini import Lamini

llm = Lamini(model_name="32ec8321e2d3cde284cd89fc554ea9584f859a456e5ecb29e298c5da6282819c")

prompt = "What are llamas?"
response = llm.generate(prompt)
print(response)
```

**Comment by edamamez** [comment]
The training bug has been fixed as well, please try running the job again! Thank you for reporting 🙌 

Feel free to reach out to info@lamini.ai with your email to get some credits as thanks!
