### ISSUE TITLE
Server Issue

### ISSUE THREAD

**Issue by teja0508** [lamini-ai/lamini#53]
Is there any way to check whether the Lamini server was down or up ?

i submitted this job: https://app.lamini.ai/train/6143. it's completed successfully. but when i refresh the browser. it is loading for a while... still loading not able to see the page.

**Comment by edamamez** [comment]
Hi @teja0508, are you able to see it in the train tab (https://app.lamini.ai/train)?

We do not currently have a status page. 🙇 

- Eda

**Comment by teja0508** [comment]
Now i can able to see this link: https://app.lamini.ai/train , @edamamez thanks.
