### ISSUE TITLE
Chinese support

### ISSUE THREAD

**Issue by llllhd** [lamini-ai/lamini#6]
Thank you for sharing! 
Does it support Chinese data generation?

**Comment by jordane95** [comment]
What do you think?

![捕获](https://user-images.githubusercontent.com/69186130/235294937-195a2499-80db-446b-bd53-58a6aaac89d4.JPG)

**Comment by greg1232** [comment]
Thanks for the request.  Do you have a favorite base model that is good at Chinese, e.g. on huggingface?

**Comment by dihin11** [comment]
chatglm-6B

**Comment by allanwakes** [comment]
Here is the link: https://huggingface.co/THUDM/chatglm-6b
It'd be great if this model could be supported.

**Comment by datalee** [comment]
> Here is the link: https://huggingface.co/THUDM/chatglm-6b It'd be great if this model could be supported.

good！

**Comment by ninazwei90** [comment]
hey all, thank you for using Lamini and requiring features! Appreciate your patience. We will let you know once we have models that support Chinese. @datalee @dihin11 @allanwakes @jordane95 I'm closing this issue for now. Please feel free to reach out to us -- we also love to hear your experience and feedback using Lamini! You can email me at nina@lamini.ai
