### ISSUE TITLE
Quick Guide to Use it with Colab?

### ISSUE THREAD

**Issue by fanbinne** [lamini-ai/lamini#7]

**Comment by greg1232** [comment]
Good idea.  We should put up a colab version...

**Comment by tytung2020** [comment]
agreed

**Comment by ninazwei90** [comment]
@fanbinne @tytung2020 hey! We now have a lot of colab examples! 

Finetuning your own LLMs: https://colab.research.google.com/drive/1mxuzGfXc_S1fUSQV4AH1Qeao_biythhx
Question-Answer LLM Finetuning: https://colab.research.google.com/drive/1S7VfBqaxM4kMJriqo8yb0QnfgI0IMYsp
Llama V2 PEFT: https://colab.research.google.com/drive/1kc92-BjRLNa9evn_IKzEMf2z2lMzNo77
Finetuned vs. Non-finetuned LLMs: https://colab.research.google.com/drive/1Tt-Su-RVMyemiucC4GduyLxU5F-wj1up

We have more walkthroughs in our docs: https://lamini-ai.github.io/
We also just released a lot of SDKs. Please see our public repos: https://github.com/lamini-ai

Also, thanks so much for using Lamini and reporting issues! We'd love to learn from you and see how we can improve Lamini for you! If you're open to a 20-30 min chat (in exchange for Lamini free credits), please email me at [nina@lamini.ai](mailto:nina@lamini.ai). Looking forward!!
