### ISSUE TITLE
ModuleNotFoundError: No module named 'llama' even after doing pip install lamini

### ISSUE THREAD

**Issue by anonymous0905** [lamini-ai/lamini#70]
I have installed lamini using  _**pip install lamini**_ also used _**pip install --upgrade --force-reinstall --ignore-installed lamini --user**_
 but I keep getting  ModuleNotFoundError: No module named 'llama'

can someone please help

**Comment by edamamez** [comment]
Hi there, what code are you trying to run? The error is correct -- there is no `llama` module but there is a `Lamini` module.


Here is an example from our docs: https://lamini-ai.github.io/inference/quick_start/
```
import lamini
# lamini.api_key = "<YOUR-LAMINI-API-KEY>"

llm = lamini.Lamini("meta-llama/Meta-Llama-3.1-8B-Instruct")
print(llm.generate("How are you?", output_type={"Response":"str"}))
```

**Comment by anonymous0905** [comment]
Got it thanks, I was using  deeplearning.ai notebook for reference.

**Comment by edamamez** [comment]
Got it, sorry that might be outdated -- we will take a look!

**Comment by ninazwei90** [comment]
> Got it thanks, I was using deeplearning.ai notebook for reference.

hi! Can you please share with us the notebook link?

**Comment by anonymous0905** [comment]
This is the course link - https://learn.deeplearning.ai/courses/finetuning-large-language-models/lesson/4/instruction-finetuning

I have uploaded a few notebooks from the course that I used for reference - [https://drive.google.com/drive/folders/1BpTaVI-obUqQRZ_TdkoNO6n2pq2c_Qw2?usp=drive_link](https://drive.google.com/drive/folders/1BpTaVI-obUqQRZ_TdkoNO6n2pq2c_Qw2?usp=drive_link)
