### ISSUE TITLE
Structured Outputs options

### ISSUE THREAD

**Issue by jjovalle99** [lamini-ai/lamini#73]
Hi Lamini team,

I did not find the information on available options for the JSON output. I know that it allows "str", " bool", "float", and "int"; but I am not sure if it handles arrays (i.e. List[str]) or similar.  The following code did not work:

```
schema: dict = {"capital": List[str]} # or {"capital": "List[str]"}
response: str = await llm.async_generate(prompt=format_llama3_prompt(user_message=user_message), output_type=schema)
```

Can you please point me to the relevant information on this?

**Comment by edamamez** [comment]
Hello! Just wanted to update you that we support lists as enums! You can learn more here: https://lamini-ai.github.io/inference/json_output/#values-other-than-strings
