### ISSUE TITLE
The Playground can't show answer？

### ISSUE THREAD

**Issue by Demoindata** [lamini-ai/lamini#8]
![image](https://user-images.githubusercontent.com/42016699/236384605-2c25cc62-01a1-4b9a-b49e-0d2f8d79e595.png)

**Comment by ninazwei90** [comment]
Hey @Demoindata! Thanks for your understanding of our delayed responses. We've been cooking up a lot of exciting features, including a new playground! https://app.lamini.ai/playground or Llama 2 playground https://app.lamini.ai/llama2

Also, thanks so much for using Lamini and reporting issues! We'd love to learn from you and see how we can improve Lamini for you! If you're open to a 20-30 min chat (in exchange for Lamini free credits), please email me at [nina@lamini.ai](mailto:nina@lamini.ai). Looking forward!!
