### ISSUE TITLE
Why does my Lamini API key configuration not take effect?

### ISSUE THREAD

**Issue by jiaenqiu** [lamini-ai/lamini#9]
![image](https://user-images.githubusercontent.com/26378685/236394956-0ca7c108-d2c1-43fd-b84a-e668e03e01c3.png)

**Comment by jiaenqiu** [comment]
@gdiamos @sharonzhou  I'd appreciate it if you could help me with this

**Comment by Demoindata** [comment]
me too API 500 error，the server problem？

**Comment by jiaenqiu** [comment]
![image](https://user-images.githubusercontent.com/26378685/236429591-d9206541-b99d-453a-8f1c-d062daf1bf4f.png)

**Comment by Demoindata** [comment]
> ![image](https://user-images.githubusercontent.com/26378685/236429591-d9206541-b99d-453a-8f1c-d062daf1bf4f.png)
这个应该是post的方法，不是get的，现在接口好了，返回200了
![image](https://user-images.githubusercontent.com/42016699/236431905-c3912579-93c5-454f-840c-2732bdc2c163.png)

**Comment by jiaenqiu** [comment]
> > ![image](https://user-images.githubusercontent.com/26378685/236429591-d9206541-b99d-453a-8f1c-d062daf1bf4f.png)
> > 这个应该是post的方法，不是get的，现在接口好了，返回200了
> > ![image](https://user-images.githubusercontent.com/42016699/236431905-c3912579-93c5-454f-840c-2732bdc2c163.png)

是的，服务ok了

**Comment by ninazwei90** [comment]
Thank you for your patience! @jiaenqiu @Demoindata Glad that your issues have been resolved! Please let us know if you need any help. Also, thanks so much for using Lamini and reporting issues! We'd love to learn from you and see how we can improve Lamini for you! If you're open to a 20-30 min chat (in exchange for Lamini free credits), please email me at [nina@lamini.ai](mailto:nina@lamini.ai). Looking forward!!
